"""
CLASS Integration Module for IDT
==================================
Provides two integration paths:

Path 1 (Recommended): Use CLASS's built-in fluid sector
    CLASS supports custom dark energy / dark fluid components via its
    "fluid" module. We generate a CLASS .ini file that specifies the
    domain as a fluid with tabulated w(z) and c_s²(z).

Path 2 (Advanced): Modify CLASS source directly
    For full control over perturbation equations, modify CLASS's
    perturbations.c to include the IDT domain as a new species.
    We provide the exact C code snippets needed.

This module generates everything needed for both paths.
"""

import numpy as np
import os


def generate_class_ini(idt_model, output_dir=".", filename="idt_run.ini",
                       output_spectra=True, lensing=True,
                       l_max=2500):
    """
    Generate a CLASS .ini parameter file for an IDT model.
    
    Uses CLASS's built-in fluid sector to represent the domain.
    CLASS supports up to 3 extra fluid species (fld, ur-like, or ncdm).
    
    For a single domain, we use the "fluid" (fld) module with
    tabulated w(a) and c_s²(a).
    
    Parameters
    ----------
    idt_model : IDTModel
        The IDT model instance.
    output_dir : str
        Directory to write the .ini file.
    filename : str
        Name of the .ini file.
    output_spectra : bool
        Whether to compute CMB power spectra.
    lensing : bool  
        Whether to compute lensing potential.
    l_max : int
        Maximum multipole.
        
    Returns
    -------
    str : path to generated .ini file
    """
    
    if len(idt_model.domains) == 0:
        raise ValueError("No domains in model — nothing to add to ΛCDM")
    
    if len(idt_model.domains) > 1:
        print("WARNING: CLASS fluid sector supports 1 custom fluid.")
        print("Using only the first domain. For multiple domains,")
        print("use Path 2 (source modification) or combine domains")
        print("into a single effective component.")
    
    domain = idt_model.domains[0]
    
    # -------------------------------------------------------
    # Build w(a) table for CLASS
    # -------------------------------------------------------
    # CLASS wants w as a function of scale factor a, tabulated
    # CLASS format: each line is "a  w(a)"
    
    n_table = 5000
    z_table = np.logspace(-2, 4.1, n_table)  # z from 0.01 to ~12000
    a_table = 1.0 / (1.0 + z_table)
    w_table = domain.w(z_table)
    
    # Sort by ascending a (CLASS expects this)
    sort_idx = np.argsort(a_table)
    a_table = a_table[sort_idx]
    w_table = w_table[sort_idx]
    
    # Write w(a) table
    wa_file = os.path.join(output_dir, "idt_w_of_a.dat")
    with open(wa_file, 'w') as f:
        f.write("# IDT domain equation of state w(a)\n")
        f.write(f"# f_dom = {domain.f_dom}, z_c = {domain.z_c}, "
                f"delta_z = {domain.delta_z}\n")
        f.write("# a    w(a)\n")
        for a, w in zip(a_table, w_table):
            f.write(f"{a:.8e}  {w:.8e}\n")
    
    # -------------------------------------------------------
    # Compute Omega_fld at z=0
    # -------------------------------------------------------
    # CLASS needs Omega_fld today as input parameter
    Omega_fld_0 = float(domain.Omega(0.0))
    
    # Adjust Omega_Lambda to maintain flatness
    Omega_Lambda_adjusted = idt_model.Omega_Lambda - Omega_fld_0
    
    # -------------------------------------------------------
    # Build .ini file
    # -------------------------------------------------------
    ini_lines = [
        "# =====================================================",
        "# IDT Cosmological Model — CLASS Parameter File",
        "# =====================================================",
        f"# Generated by IDT CLASS module",
        f"# Domain: f_dom={domain.f_dom}, z_c={domain.z_c}, "
        f"delta_z={domain.delta_z}",
        f"# c_s^2 = {domain.c_s2}",
        "#",
        "",
        "# --- Cosmological parameters ---",
        f"H0 = {idt_model.H0}",
        f"omega_b = {idt_model.Omega_b * (idt_model.H0/100)**2:.6f}",
        f"omega_cdm = {(idt_model.Omega_m - idt_model.Omega_b) * (idt_model.H0/100)**2:.6f}",
        "",
        "# --- Radiation ---",
        "T_cmb = 2.7255",
        "N_ur = 2.0328",
        "N_ncdm = 1",
        "m_ncdm = 0.06",
        "",
        "# --- Dark energy (cosmological constant, adjusted for flatness) ---",
        f"Omega_Lambda = {Omega_Lambda_adjusted:.8f}",
        "",
        "# --- IDT Domain as fluid ---",
        f"Omega_fld = {Omega_fld_0:.8e}",
        "use_ppf = yes",
        f"fluid_equation_of_state = CLP",
        "",
        "# For CLP (custom linear perturbation):",
        "# CLASS will read w(a) from table",
        f"w0_fld = {float(domain.w(0.01)):.6f}",
        f"wa_fld = 0",  # Not used with table, but required
        f"cs2_fld = {domain.c_s2}",
        "",
    ]
    
    # Alternative: if CLASS version supports tabulated w
    ini_lines.extend([
        "# --- ALTERNATIVE: Tabulated w(a) ---",
        "# Uncomment below and comment out w0_fld/wa_fld above",
        "# if your CLASS version supports input_w_over_a_file:",
        f"# input_w_over_a_file = {os.path.abspath(wa_file)}",
        "",
    ])
    
    # Output settings
    if output_spectra:
        ini_lines.extend([
            "# --- Output ---",
            f"output = tCl,pCl,lCl" if lensing else f"output = tCl,pCl",
            f"l_max_scalars = {l_max}",
        ])
        if lensing:
            ini_lines.append("lensing = yes")
    
    ini_lines.extend([
        "",
        "# --- Precision ---",
        "tol_background_integration = 1.e-6",
        "tol_perturbations_integration = 1.e-6",
        "",
        "# --- Background output for diagnostics ---",
        "write background = yes",
        f"background_output_file = {os.path.join(output_dir, 'idt_background.dat')}",
    ])
    
    # Write .ini file
    ini_path = os.path.join(output_dir, filename)
    with open(ini_path, 'w') as f:
        f.write('\n'.join(ini_lines))
    
    print(f"CLASS .ini file written to: {ini_path}")
    print(f"w(a) table written to: {wa_file}")
    print(f"Omega_fld(z=0) = {Omega_fld_0:.4e}")
    print(f"Omega_Lambda (adjusted) = {Omega_Lambda_adjusted:.6f}")
    
    return ini_path


def generate_class_source_patch(domain, output_dir="."):
    """
    Generate C code snippets for direct CLASS source modification.
    
    This is Path 2: instead of using the built-in fluid module,
    modify CLASS's source/background.c and source/perturbations.c
    to include the IDT domain as a new species.
    
    This gives full control over the perturbation equations and
    avoids limitations of the built-in fluid sector.
    
    Parameters
    ----------
    domain : IDTDomain
        The domain component.
    output_dir : str
        Where to write the patch files.
    """
    
    # -------------------------------------------------------
    # Background patch: add domain to Friedmann equation
    # -------------------------------------------------------
    bg_patch = f"""
/* =====================================================
 * IDT DOMAIN — Background contribution
 * Add to: source/background.c, inside background_functions()
 * =====================================================
 * 
 * Parameters:
 *   f_dom   = {domain.f_dom}
 *   z_c     = {domain.z_c}
 *   delta_z = {domain.delta_z}
 *   sigma_ln = {domain._sigma_ln:.8f}
 *   Omega_peak = {domain._Omega_peak:.8e}
 *
 * Place this after the standard ΛCDM components are computed.
 */

/* IDT domain energy density */
double z_idt = 1.0/a - 1.0;  /* redshift from scale factor */
double ln_ratio_idt = log((1.0 + z_idt) / (1.0 + {domain.z_c}));
double sigma_ln_idt = {domain._sigma_ln:.8e};
double Omega_peak_idt = {domain._Omega_peak:.8e};

double rho_idt = Omega_peak_idt * exp(-0.5 * ln_ratio_idt * ln_ratio_idt 
                                       / (sigma_ln_idt * sigma_ln_idt));

/* Add to Friedmann equation */
/* pvecback[pba->index_bg_rho_idt] = rho_idt * pba->H0 * pba->H0; */
/* Then add rho_idt to the total: */
/* rho_tot += rho_idt; */

/* IDT equation of state (derived from conservation) */
double w_idt = -1.0 + (1.0/3.0) * (-ln_ratio_idt / (sigma_ln_idt * sigma_ln_idt));

/* IDT pressure */
double p_idt = w_idt * rho_idt;
"""
    
    # -------------------------------------------------------
    # Perturbation patch: δ and θ equations
    # -------------------------------------------------------
    pert_patch = f"""
/* =====================================================
 * IDT DOMAIN — Perturbation equations (synchronous gauge)
 * Add to: source/perturbations.c, inside perturb_derivs()
 * =====================================================
 *
 * Fluid perturbation equations for the IDT domain:
 *
 * δ̇_idt = -(1+w_idt)(θ_idt + ḣ/2) 
 *          - 3aH(c_s² - w_idt)δ_idt
 *          - 9(aH)²(1+w_idt)(c_s² - c_a²)θ_idt/k²
 *
 * θ̇_idt = -aH(1 - 3w_idt)θ_idt 
 *          + c_s²·k²·δ_idt/(1+w_idt)
 *          + ...  (anisotropic stress terms, set to 0 here)
 *
 * Parameters:
 *   c_s^2 = {domain.c_s2}  (rest-frame sound speed squared)
 *   c_a^2 = w - w'/(3(1+w))  (adiabatic sound speed, computed)
 */

double cs2_idt = {domain.c_s2};

/* w_idt and its derivative are computed from background */
double w_idt = ppw->pvecback[pba->index_bg_w_idt];

/* dw/dlna from the profile: */
/* For log-normal: dw/dlna = -(1/3) * d²(ln ρ)/d(ln(1+z))² * ... */
/* In practice, compute numerically or store in background table */
double dw_dlna_idt = 0.0;  /* FILL IN from background interpolation */

double wpw_idt = 1.0 + w_idt;
double ca2_idt = (fabs(wpw_idt) > 1e-10) ? 
    w_idt - dw_dlna_idt / (3.0 * wpw_idt) : w_idt;

/* Density contrast equation */
double delta_idt = ppw->pvecperturbations[ppw->index_pt_delta_idt];
double theta_idt = ppw->pvecperturbations[ppw->index_pt_theta_idt];

double delta_idt_prime = 
    - wpw_idt * (theta_idt + 0.5 * ppw->pvecmetric[ppw->index_mt_h_prime])
    - 3.0 * a * pvecback[pba->index_bg_H] * (cs2_idt - w_idt) * delta_idt
    - 9.0 * pow(a * pvecback[pba->index_bg_H], 2) * wpw_idt 
      * (cs2_idt - ca2_idt) * theta_idt / (k * k);

/* Velocity divergence equation */
double theta_idt_prime =
    - a * pvecback[pba->index_bg_H] * (1.0 - 3.0 * w_idt) * theta_idt;

if (fabs(wpw_idt) > 1e-10) {{
    theta_idt_prime += cs2_idt * k * k * delta_idt / wpw_idt;
}}

/* No anisotropic stress (σ_idt = 0) */

/* Store derivatives */
ppw->pvecperturbations_prime[ppw->index_pt_delta_idt] = delta_idt_prime;
ppw->pvecperturbations_prime[ppw->index_pt_theta_idt] = theta_idt_prime;
"""
    
    # -------------------------------------------------------
    # Initial conditions patch
    # -------------------------------------------------------
    ic_patch = f"""
/* =====================================================
 * IDT DOMAIN — Initial conditions (adiabatic)
 * Add to: source/perturbations.c, inside perturb_initial_conditions()
 * =====================================================
 *
 * For adiabatic initial conditions, all species share the same
 * initial curvature perturbation. The domain perturbations are
 * initialized as:
 *
 * δ_idt = (1 + w_idt) · δ_γ / (1 + w_γ)  
 *        = (3/4)(1 + w_idt) · δ_γ    [since w_γ = 1/3]
 *
 * θ_idt = θ_γ
 *
 * This ensures adiabatic mode consistency.
 * For isocurvature modes: set δ_idt = 0 initially.
 */

double w_idt_ini = -1.0 + (1.0/3.0) * 
    (-log((1.0 + z_ini) / (1.0 + {domain.z_c})) 
     / ({domain._sigma_ln:.8e} * {domain._sigma_ln:.8e}));

double wpw_idt_ini = 1.0 + w_idt_ini;

/* Adiabatic initial conditions */
ppw->pvecperturbations[ppw->index_pt_delta_idt] = 
    0.75 * wpw_idt_ini * delta_gamma_ini;
ppw->pvecperturbations[ppw->index_pt_theta_idt] = theta_gamma_ini;
"""
    
    # Write patch files
    files = {
        'idt_background_patch.c': bg_patch,
        'idt_perturbations_patch.c': pert_patch,
        'idt_initial_conditions_patch.c': ic_patch,
    }
    
    for fname, content in files.items():
        path = os.path.join(output_dir, fname)
        with open(path, 'w') as f:
            f.write(content)
        print(f"Written: {path}")
    
    return files


def generate_classy_wrapper(output_dir="."):
    """
    Generate a Python wrapper that uses classy (CLASS Python bindings)
    to run IDT models and extract spectra.
    
    This is the recommended way to run CLASS with IDT for quick
    perturbation-level sanity checks.
    """
    
    wrapper_code = '''"""
IDT + classy wrapper
=====================
Quick perturbation-level sanity check using CLASS Python bindings.

Requirements:
    pip install classy  (or build CLASS with Python support)
    
Usage:
    python idt_classy_wrapper.py
"""

import numpy as np
import matplotlib.pyplot as plt

try:
    from classy import Class
except ImportError:
    print("ERROR: classy not installed.")
    print("Install CLASS with Python bindings:")
    print("  git clone https://github.com/lesgourg/class_public.git")
    print("  cd class_public")
    print("  make")
    print("  cd python && python setup.py install")
    raise

import sys
sys.path.insert(0, '.')
from idt_domain import IDTDomain, IDTModel
from cosmology_base import E2_LCDM


def run_lcdm_baseline():
    """Run standard ΛCDM for comparison."""
    cosmo = Class()
    cosmo.set({
        'output': 'tCl,pCl,lCl',
        'lensing': 'yes',
        'l_max_scalars': 2500,
        'H0': 67.36,
        'omega_b': 0.02237,
        'omega_cdm': 0.1200,
        'T_cmb': 2.7255,
        'N_ur': 2.0328,
        'N_ncdm': 1,
        'm_ncdm': 0.06,
    })
    cosmo.compute()
    
    cls = cosmo.lensed_cl(2500)
    bg = cosmo.get_background()
    
    result = {
        'ell': np.arange(len(cls['tt'])),
        'tt': cls['tt'],
        'ee': cls['ee'],
        'te': cls['te'],
        'pp': cls['pp'],
        'bg': bg,
    }
    
    # Sound horizon
    thermo = cosmo.get_thermodynamics()
    result['rs_drag'] = cosmo.rs_drag()
    result['H0'] = cosmo.Hubble(0) * 2.998e5  # Convert to km/s/Mpc
    
    cosmo.struct_cleanup()
    cosmo.empty()
    
    return result


def run_idt_as_fluid(f_dom, z_c, delta_z, cs2=1.0):
    """
    Run IDT domain as CLASS fluid species.
    
    Uses CLASS's built-in fluid sector with PPF approximation.
    This handles the perturbation equations automatically.
    """
    domain = IDTDomain.__new__(IDTDomain)
    # Manually set attributes without triggering __init__
    # which requires the cosmology_base import inside the class
    domain.f_dom = f_dom
    domain.z_c = z_c
    domain.delta_z = delta_z
    domain.c_s2 = cs2
    domain._sigma_ln = delta_z / (1 + z_c)
    
    # Compute w at z=0 for CLASS
    log_ratio_0 = np.log(1.0 / (1 + z_c))
    w0 = -1.0 + (1.0/3.0) * (-log_ratio_0 / domain._sigma_ln**2)
    
    # Omega_fld at z=0
    E2_zc = E2_LCDM(z_c)
    Omega_peak = f_dom / (1 - f_dom) * E2_zc
    rho_shape_0 = np.exp(-0.5 * (log_ratio_0 / domain._sigma_ln)**2)
    Omega_fld_0 = Omega_peak * rho_shape_0
    
    cosmo = Class()
    
    params = {
        'output': 'tCl,pCl,lCl',
        'lensing': 'yes',
        'l_max_scalars': 2500,
        'H0': 67.36,
        'omega_b': 0.02237,
        'omega_cdm': 0.1200,
        'T_cmb': 2.7255,
        'N_ur': 2.0328,
        'N_ncdm': 1,
        'm_ncdm': 0.06,
        # Fluid sector for IDT domain
        'Omega_fld': Omega_fld_0,
        'w0_fld': w0,
        'wa_fld': 0,
        'cs2_fld': cs2,
        'use_ppf': 'yes',
    }
    
    cosmo.set(params)
    
    try:
        cosmo.compute()
    except Exception as e:
        print(f"CLASS computation failed: {e}")
        print("This may indicate perturbation instabilities.")
        cosmo.struct_cleanup()
        cosmo.empty()
        return None
    
    cls = cosmo.lensed_cl(2500)
    
    result = {
        'ell': np.arange(len(cls['tt'])),
        'tt': cls['tt'],
        'ee': cls['ee'],
        'te': cls['te'],
        'pp': cls['pp'],
        'rs_drag': cosmo.rs_drag(),
        'H0': cosmo.Hubble(0) * 2.998e5,
        'params': params,
    }
    
    cosmo.struct_cleanup()
    cosmo.empty()
    
    return result


def sanity_check(f_dom=0.10, z_c=2000, delta_z=600):
    """
    Run the perturbation-level sanity check.
    
    Compares ΛCDM and IDT CMB spectra, checking:
    1. Peak positions (should shift with r_d)
    2. Relative peak heights
    3. Damping tail behavior
    4. Lensing amplitude
    """
    print("=" * 60)
    print("IDT Perturbation-Level Sanity Check")
    print("=" * 60)
    print(f"Domain: f_dom={f_dom}, z_c={z_c}, Δz={delta_z}")
    print()
    
    print("Running ΛCDM baseline...")
    lcdm = run_lcdm_baseline()
    print(f"  r_d = {lcdm['rs_drag']:.2f} Mpc")
    
    print(f"Running IDT (f={f_dom}, z_c={z_c})...")
    idt = run_idt_as_fluid(f_dom, z_c, delta_z)
    
    if idt is None:
        print("FAILED — IDT produced perturbation instabilities")
        return
    
    print(f"  r_d = {idt['rs_drag']:.2f} Mpc")
    print(f"  Δr_d/r_d = {(idt['rs_drag']-lcdm['rs_drag'])/lcdm['rs_drag']*100:.2f}%")
    
    # Plot comparison
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle(f'IDT Perturbation Check: f={f_dom}, z_c={z_c}', 
                 fontsize=14, fontweight='bold')
    
    ell = lcdm['ell'][2:]
    fac = ell * (ell + 1) / (2 * np.pi)  # standard CMB normalization
    
    # TT spectrum
    ax = axes[0, 0]
    ax.plot(ell, fac * lcdm['tt'][2:] * 1e12, 'k-', lw=1, label='ΛCDM')
    ax.plot(ell, fac * idt['tt'][2:] * 1e12, 'r--', lw=1, label='IDT')
    ax.set_xlabel('ℓ')
    ax.set_ylabel('ℓ(ℓ+1)C_ℓ^TT / 2π [μK²]')
    ax.set_title('Temperature Power Spectrum')
    ax.legend()
    ax.set_xlim(2, 2500)
    ax.grid(True, alpha=0.3)
    
    # TT residual
    ax = axes[0, 1]
    ratio = idt['tt'][2:] / lcdm['tt'][2:]
    ax.plot(ell, (ratio - 1) * 100, 'r-', lw=1)
    ax.axhline(0, color='k', lw=0.5)
    ax.set_xlabel('ℓ')
    ax.set_ylabel('ΔC_ℓ^TT / C_ℓ^TT [%]')
    ax.set_title('TT Fractional Residual')
    ax.set_xlim(2, 2500)
    ax.grid(True, alpha=0.3)
    
    # EE spectrum
    ax = axes[1, 0]
    ax.plot(ell, fac * lcdm['ee'][2:] * 1e12, 'k-', lw=1, label='ΛCDM')
    ax.plot(ell, fac * idt['ee'][2:] * 1e12, 'r--', lw=1, label='IDT')
    ax.set_xlabel('ℓ')
    ax.set_ylabel('ℓ(ℓ+1)C_ℓ^EE / 2π [μK²]')
    ax.set_title('E-mode Polarization')
    ax.legend()
    ax.set_xlim(2, 2500)
    ax.grid(True, alpha=0.3)
    
    # Lensing
    ax = axes[1, 1]
    ax.plot(ell, fac * lcdm['pp'][2:] * 1e7, 'k-', lw=1, label='ΛCDM')
    ax.plot(ell, fac * idt['pp'][2:] * 1e7, 'r--', lw=1, label='IDT')
    ax.set_xlabel('ℓ')
    ax.set_ylabel('ℓ(ℓ+1)C_ℓ^φφ / 2π [×10⁷]')
    ax.set_title('Lensing Power Spectrum')
    ax.legend()
    ax.set_xlim(2, 2500)
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('idt_perturbation_check.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"\\nPlot saved: idt_perturbation_check.png")
    
    # Summary diagnostics
    print(f"\\n--- Diagnostics ---")
    print(f"  max |ΔC_ℓ^TT/C_ℓ^TT| = {np.max(np.abs(ratio-1))*100:.2f}%")
    print(f"  Peak 1 shift visible: check plot")
    print(f"  Damping tail stable: {np.all(np.isfinite(idt['tt']))}")
    
    return lcdm, idt


if __name__ == "__main__":
    # Run default sanity check
    sanity_check(f_dom=0.10, z_c=2000, delta_z=600)
    
    # Also test a few other configurations
    for f, zc in [(0.05, 1500), (0.15, 2000), (0.20, 3000)]:
        print(f"\\n{'='*60}")
        sanity_check(f_dom=f, z_c=zc, delta_z=int(0.3*zc))
'''
    
    wrapper_path = os.path.join(output_dir, "idt_classy_wrapper.py")
    with open(wrapper_path, 'w') as f:
        f.write(wrapper_code)
    
    print(f"Written: {wrapper_path}")
    return wrapper_path
